
###
//GET dla kraju i kategorii
GET http://localhost:8081/bmi/raw?country=POL&category=underweight
Authorization: Bearer TOKEN


###
//GET z filtrami
GET http://localhost:8081/bmi/filtered?country=USA&category=obese&year=2015&sex=FMLE
Authorization: Bearer TOKEN

###
//GET bmi z kategorią
POST http://localhost:8081/bmi/my
Authorization: Bearer TOKEN
Content-Type: application/json

{
  "height": 1.75,
  "country": "POL"
}

###
//GET bmi z porownaniem
POST http://localhost:8081/bmi/compare
Authorization: Bearer TOKEN
Content-Type: application/json

{
  "height": 1.75,
  "country": "POL"
}