
###
//GET dla kraju i kategorii
GET https://diet-master.herokuapp.com/bmi/raw?country=POL&category=underweight
Authorization: Bearer TOKEN_CHARACTERS


###
//GET z filtrami
GET https://diet-master.herokuapp.com/bmi/filtered?country=USA&category=obese&year=2015&sex=FMLE
Authorization: Bearer TOKEN_CHARACTERS

###
//GET bmi z kategorią
POST https://diet-master.herokuapp.com/bmi/my
Authorization: Bearer TOKEN_CHARACTERS
Content-Type: application/json

{
  "height": 1.75,
  "country": "POL"
}

###
//GET bmi z porownaniem
POST https://diet-master.herokuapp.com/bmi/compare
Authorization: Bearer TOKEN_CHARACTERS
Content-Type: application/json

{
  "height": 1.75,
  "country": "POL"
}