PUT https://diet-master.herokuapp.com/meals
Authorization: Bearer TOKEN_CHARACTERS
Content-Type: application/json

{
  "id":1,
  "name":"Nowa nazwa",
  "description":"nowy opis",
  "type":3
}
###
//wszystkie posilki ze wskazanej diety
GET https://diet-master.herokuapp.com/meals/diet/1
Authorization: Bearer TOKEN_CHARACTERS

###
GET https://diet-master.herokuapp.com/meals/1
Authorization: Bearer TOKEN_CHARACTERS


