###
POST http://localhost:8081/registration
Content-Type: application/json

{
  "firstName": "_",
  "lastName": "_",
  "email": "_@edu.p.lodz.pl",
  "password": "qwerty123"
}

###
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "_@edu.p.lodz.pl",
  "password": "qwerty123"
}

