###
POST https://diet-master.herokuapp.com/registration
Content-Type: application/json

{
  "firstName": "_",
  "lastName": "_",
  "email": "_@edu.p.lodz.pl",
  "password": "qwerty123"
}

###
POST https://diet-master.herokuapp.com/login
Content-Type: application/json

{
  "username": "_@edu.p.lodz.pl",
  "password": "qwerty123"
}

